version: '3.4'

services:
  conferenceapi.web:
    image: ${DOCKER_REGISTRY-}conferenceapiweb
    build:
      context: .
      dockerfile: ConferenceAPI.Web/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"